name: ezmanagement
description: EZ Management App Flutter
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  easy_localization: ^3.0.7+1
  overlay_support: ^2.0.1
  bmprogresshud: 1.0.3
  either_dart: 1.0.0
  cupertino_icons: ^1.0.8
  firebase_core: ^2.30.0
  flutter_riverpod: 2.6.1
  http: ^1.4.0
  intl: ^0.20.2
  flutter_svg: ^2.2.0
  fluttertoast: ^8.2.4
  riverpod_annotation: 2.6.1
  sane_uuid: ^1.1.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.6.5
  build_runner: ^2.4.6
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  msix: ^3.16.9

flutter:

  uses-material-design: true
  generate: true
  
  assets:
    - assets/
    - assets/images/
    - assets/translations/

msix_config:
  display_name: EZ Management
  publisher_display_name: EZ MANAGEMENT
  languages: en-US, es-ES
  capabilities: internetClient, location, microphone, webcam, privateNetworkClientServer
  