// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjWn12GiCd4CP6vgF9XFR-nOMGXqusB7w',
    appId: '1:1096224199835:web:ea18991c2b25e71f7de23e',
    messagingSenderId: '1096224199835',
    projectId: 'ezmanagement-2828',
    authDomain: 'ezmanagement-2828.firebaseapp.com',
    storageBucket: 'ezmanagement-2828.firebasestorage.app',
    measurementId: 'G-8TXZHXLGVT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3CtbCXgyj6VNjdP62d41xPLQ_M-W9F1s',
    appId: '1:1096224199835:android:bd0c5fd001a962c57de23e',
    messagingSenderId: '1096224199835',
    projectId: 'ezmanagement-2828',
    storageBucket: 'ezmanagement-2828.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzIce0Qdu4O7224Z1uLkPhlWQjjuqPr_o',
    appId: '1:1096224199835:ios:7a0387dd5836da037de23e',
    messagingSenderId: '1096224199835',
    projectId: 'ezmanagement-2828',
    storageBucket: 'ezmanagement-2828.firebasestorage.app',
    iosBundleId: 'com.example.ezmanagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzIce0Qdu4O7224Z1uLkPhlWQjjuqPr_o',
    appId: '1:1096224199835:ios:7a0387dd5836da037de23e',
    messagingSenderId: '1096224199835',
    projectId: 'ezmanagement-2828',
    storageBucket: 'ezmanagement-2828.firebasestorage.app',
    iosBundleId: 'com.example.ezmanagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjWn12GiCd4CP6vgF9XFR-nOMGXqusB7w',
    appId: '1:1096224199835:web:50ae864ddc748c7f7de23e',
    messagingSenderId: '1096224199835',
    projectId: 'ezmanagement-2828',
    authDomain: 'ezmanagement-2828.firebaseapp.com',
    storageBucket: 'ezmanagement-2828.firebasestorage.app',
    measurementId: 'G-LX8RKZ5QQ1',
  );

}