// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYGrQFeRi_tsibJ2n0xJoDN-ZfHf4EYu8',
    appId: '1:187488371361:web:47ba3307735203cd8326e0',
    messagingSenderId: '187488371361',
    projectId: 'invumycrew',
    authDomain: 'invumycrew.firebaseapp.com',
    databaseURL: 'https://invumycrew-default-rtdb.firebaseio.com',
    storageBucket: 'invumycrew.firebasestorage.app',
    measurementId: 'G-BDMYTT6Q11',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHy-flWfysQQ8CUu3bAzlKUf5y7dqAS2g',
    appId: '1:187488371361:android:c88fa92c3341230c8326e0',
    messagingSenderId: '187488371361',
    projectId: 'invumycrew',
    databaseURL: 'https://invumycrew-default-rtdb.firebaseio.com',
    storageBucket: 'invumycrew.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcjBU33TsuE0nA8gCRTLS6aExvOLO38Ok',
    appId: '1:187488371361:ios:33cda8c14716e3dd8326e0',
    messagingSenderId: '187488371361',
    projectId: 'invumycrew',
    databaseURL: 'https://invumycrew-default-rtdb.firebaseio.com',
    storageBucket: 'invumycrew.firebasestorage.app',
    iosBundleId: 'com.example.ezmanagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcjBU33TsuE0nA8gCRTLS6aExvOLO38Ok',
    appId: '1:187488371361:ios:33cda8c14716e3dd8326e0',
    messagingSenderId: '187488371361',
    projectId: 'invumycrew',
    databaseURL: 'https://invumycrew-default-rtdb.firebaseio.com',
    storageBucket: 'invumycrew.firebasestorage.app',
    iosBundleId: 'com.example.ezmanagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYGrQFeRi_tsibJ2n0xJoDN-ZfHf4EYu8',
    appId: '1:187488371361:web:7cf16d6e656565388326e0',
    messagingSenderId: '187488371361',
    projectId: 'invumycrew',
    authDomain: 'invumycrew.firebaseapp.com',
    databaseURL: 'https://invumycrew-default-rtdb.firebaseio.com',
    storageBucket: 'invumycrew.firebasestorage.app',
    measurementId: 'G-947TS9CDT9',
  );

}