name: ezmanagement
description: EZ Management App Flutter
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  easy_localization: ^3.0.7+1
  overlay_support: ^2.0.1
  bmprogresshud: 1.0.3
  either_dart: 1.0.0
  cupertino_icons: ^1.0.8
  firebase_core: ^2.30.0
  flutter_riverpod: 2.6.1
  http: ^1.4.0
  intl: ^0.20.2
  flutter_svg: ^2.2.0
  fluttertoast: ^8.2.4
  riverpod_annotation: 2.6.1
  sane_uuid: ^1.1.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.6.5
  build_runner: ^2.4.6
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  msix: ^3.16.9

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/ez_management_app_logo.png"
  windows:
    generate: true
    image_path: "assets/images/ez_management_app_logo.png"
    icon_size: 48

flutter:
  fonts:
    - family: OpenSansHebrew
      fonts:
        - asset: assets/fonts/open_sans_hebrew/OpenSansHebrew-Light.ttf
          weight: 300
        - asset: assets/fonts/open_sans_hebrew/OpenSansHebrew-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/open_sans_hebrew/OpenSansHebrew-Regular.ttf
          weight: 400
        - asset: assets/fonts/open_sans_hebrew/OpenSansHebrew-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/open_sans_hebrew/OpenSansHebrew-Bold.ttf
          weight: 700
        - asset: assets/fonts/open_sans_hebrew/OpenSansHebrew-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/open_sans_hebrew/OpenSansHebrew-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/open_sans_hebrew/OpenSansHebrew-ExtraBoldItalic.ttf
          weight: 800
          style: italic

    - family: OpenSansHebrewCondensed
      fonts:
        - asset: assets/fonts/open_sans_hebrew_condensed/OpenSansHebrewCondensed-Light.ttf
          weight: 300
        - asset: assets/fonts/open_sans_hebrew_condensed/OpenSansHebrewCondensed-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/open_sans_hebrew_condensed/OpenSansHebrewCondensed-Regular.ttf
          weight: 400
        - asset: assets/fonts/open_sans_hebrew_condensed/OpenSansHebrewCondensed-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/open_sans_hebrew_condensed/OpenSansHebrewCondensed-Bold.ttf
          weight: 700
        - asset: assets/fonts/open_sans_hebrew_condensed/OpenSansHebrewCondensed-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/open_sans_hebrew_condensed/OpenSansHebrewCondensed-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/open_sans_hebrew_condensed/OpenSansHebrewCondensed-ExtraBoldItalic.ttf
          weight: 800
          style: italic

  uses-material-design: true
  generate: true
  
  assets:
    - assets/
    - assets/images/
    - assets/images/icons/
    - assets/translations/
    - assets/fonts/

msix_config:
  display_name: EZ Management
  publisher_display_name: EZ MANAGEMENT
  languages: en-US, es-ES
  capabilities: internetClient, location, microphone, webcam, privateNetworkClientServer
  